### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-js-conditionals-uMDt4P#1]
@egillespie Can you take a look at this? It's [hosted here](https://kisyular.github.io/MI-449-SS17-740-js-conditionals-uMDt4P/) and meets the following criteria:

- [x] Use the `prompt` and `confirm` functions (each at least once) to collect choices from the user (the entire story will take place in dialog boxes, so your `body` element could actually be empty, apart from the `script` element to include your JavaScript)
- [x] Use `if`, `else if`, and `else` to branch the story, based on user choices
- [x] In at least one branch, there should be at least 3 choices for the user to make
- [x] Include at least one branch where different things can happen each time with `Math.random()`
- [x] Use a logical operator (`&&` or `||`) at least once, where it makes sense
- [x] It should be impossible for an error to ever occur when playing your game, including handling for `null`/`undefined` where appropriate
- [x] All string input should be normalized, so that extra whitespace or a letter that's the wrong case will never cause a failed match
- [x] At least one number value is collected and used in a comparison (don't forget to convert it into a number first)
- [x] Don't get _too_ carried away -- it can be tempting to build a complex video game, but remember, you can always come back and build on this project later

**Comment by egillespie** [comment]
Whoa, you picked the right person to review this. I love horror! :feelsgood:

### Notes about the game

Before I looked at any code, I played through the game a bunch of times. Thanks for being creative with the theme, too!

The only peculiar thing I noticed was when I cut my hand off. The next prompt mentions blue and red keys. The next prompt says the keys are blue and green, or I can choose randomly. If I choose randomly, the next prompt sometimes mentions a red key again. This was a little confusing, but you probably just need to replace any reference to the red key with the green key.

### Code tips

#### Usually JavaScript goes in `body`

Scripts that are in the `head` will run before the `body` is displayed. Since you don't have any content in `body`, this isn't a big deal. In a normal app, you probably want your JavaScript to run after the page displays in case you need to add event listeners or interact with the page.

The general tip: put `script` elements at the very end of the `body`.

#### Shortening your code

It looks like you captured all of the material from the lesson, but I have some suggestions to reduce the amount of code you write:

1. `year !== null && year !== undefined && year.length === 4` can be shortened to `year && year.length === 4`. If `year` is truthy, then it will have a value and you can safely get the length from it.
2. `(2017 - year) > 18` can be simplified as `2017 - year > 18`. Arithmetic operators are evaluated before comparison operators, so the parentheses aren't necessary. Good job being cautious, though!
3. You can chain methods to normalize strings. For example, you can do this: `leghand = leghand.trim().toLowerCase()`.
4. Another way to avoid `leghand !== null || leghand !== undefined` is to assign an empty string to `leghand` if it is falsy: `leghand = leghand || ''`. Then you don't even need to check if `leghand` is `null` or `undefined`.

---

After you’ve made these changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by kisyular** [comment]
@egillespie I made the changes you suggested. Kindly let me know

**Comment by egillespie** [comment]
Hi @kisyular, re-reading my previous comment, I didn't do a good job explaining the impact of using `leghand = leghand || ''`.

When you use `||` to make sure `leghand` has a valid value, it means you can completely remove the `if` that tests whether `leghand` has a truthy value.

So this:

```js
if (leghand) {
  leghand = leghand || ''
  // ... other code
} else {
  alert(error)
}
```

Becomes this:

```js
leghand = leghand || ''
// ... other code
```

If that makes sense, can you update the two places where you are using `||` like that and let me know when you've published your changes?

Thanks!

**Comment by kisyular** [comment]
@egillespie, I update the code as you suggested

**Comment by egillespie** [comment]
Niiiiiiiice. Looks great and you shaved off almost 20 lines of code! :shipit:
